// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// addition //
// -------- //

#define addition_wrap_target 0
#define addition_wrap 8

static const uint16_t addition_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0xa02f, //  1: mov    x, !osr                    
    0x80a0, //  2: pull   block                      
    0xa047, //  3: mov    y, osr                     
    0x0006, //  4: jmp    6                          
    0x0046, //  5: jmp    x--, 6                     
    0x0085, //  6: jmp    y--, 5                     
    0xa0c9, //  7: mov    isr, !x                    
    0x8020, //  8: push   block                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program addition_program = {
    .instructions = addition_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config addition_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + addition_wrap_target, offset + addition_wrap);
    return c;
}

static inline void addition_program_init(PIO pio, uint sm, uint offset) {
	pio_sm_config c = addition_program_get_default_config(offset);
	pio_sm_init(pio, sm, offset, &c);
	pio_sm_set_enabled(pio, sm, true);
}

#endif

