
#define IO_EXIT      0x00
#define IO_STDIN     0x01
#define IO_STDOUT    0x01
#define IO_STDERR    0x02

#define IO_SCRATCH_0 0x10
#define IO_SCRATCH_1 0x11
#define IO_SCRATCH_2 0x12
#define IO_SCRATCH_3 0x13
#define IO_SCRATCH_4 0x14
#define IO_SCRATCH_5 0x15
#define IO_SCRATCH_6 0x16
#define IO_SCRATCH_7 0x17
#define IO_SCRATCH_8 0x18
#define IO_SCRATCH_9 0x19
#define IO_SCRATCH_A 0x1a
#define IO_SCRATCH_B 0x1b
#define IO_SCRATCH_C 0x1c
#define IO_SCRATCH_D 0x1d
#define IO_SCRATCH_E 0x1e
#define IO_SCRATCH_F 0x1f
