// BLE HCI (Host Controller Interface) status codes.

pub const StatusCode = enum(u8) {
    success = 0x00,
    unknown_btle_command = 0x01,
    unknown_connection_identifier = 0x02,
    authentication_failure = 0x05,
    pin_or_key_missing = 0x06,
    memory_capacity_exceeded = 0x07,
    connection_timeout = 0x08,
    command_disallowed = 0x0C,
    invalid_btle_command_parameters = 0x12,
    remote_user_terminated_connection = 0x13,
    remote_dev_termination_due_to_low_resources = 0x14,
    remote_dev_termination_due_to_power_off = 0x15,
    local_host_terminated_connection = 0x16,
    unsupported_remote_feature = 0x1A,
    invalid_lmp_parameters = 0x1E,
    unspecified_error = 0x1F,
    lmp_response_timeout = 0x22,
    lmp_error_transaction_collision = 0x23,
    lmp_pdu_not_allowed = 0x24,
    instant_passed = 0x28,
    pairing_with_unit_key_unsupported = 0x29,
    different_transaction_collision = 0x2A,
    parameter_out_of_mandatory_range = 0x30,
    controller_busy = 0x3A,
    conn_interval_unacceptable = 0x3B,
    directed_advertiser_timeout = 0x3C,
    conn_terminated_due_to_mic_failure = 0x3D,
    conn_failed_to_be_established = 0x3E,
    _,
};
