// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// squarewave_fast //
// --------------- //

#define squarewave_fast_wrap_target 1
#define squarewave_fast_wrap 2

static const uint16_t squarewave_fast_program_instructions[] = {
    0xe081, //  0: set    pindirs, 1                 
            //     .wrap_target
    0xe001, //  1: set    pins, 1                    
    0xe000, //  2: set    pins, 0                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program squarewave_fast_program = {
    .instructions = squarewave_fast_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config squarewave_fast_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + squarewave_fast_wrap_target, offset + squarewave_fast_wrap);
    return c;
}
#endif

