const microzig = @import("microzig");
const mmio = microzig.mmio;

pub const types = @import("../../types.zig");

pub const CHMOD = enum(u3) {
    /// Electronic codebook
    ECB = 0x0,
    /// Cipher-block chaining
    CBC = 0x1,
    /// Counter mode
    CTR = 0x2,
    /// Galois counter mode and Galois message authentication code
    GCM_GMAC = 0x3,
    /// Counter with CBC-MAC
    CCM = 0x4,
    _,
};

pub const DATATYPE = enum(u2) {
    /// No swapping (32-bit data).
    None = 0x0,
    /// Half-word swapping (16-bit data)
    HalfWord = 0x1,
    /// Byte swapping (8-bit data)
    Byte = 0x2,
    /// Bit-level swapping
    Bit = 0x3,
};

pub const KEYSEL = enum(u3) {
    /// Software key, loaded in key registers SAES_KEYx
    SoftwareKey = 0x0,
    /// Derived hardware unique key
    DHUK = 0x1,
    /// Boot hardware key
    BHK = 0x2,
    /// XOR of DHUK and BHK
    XOR_DHUK_BHK = 0x4,
    _,
};

pub const KEYSIZE = enum(u1) {
    /// 128-bit
    Bits128 = 0x0,
    /// 256-bit
    Bits256 = 0x1,
};

pub const KMOD = enum(u2) {
    /// AES peripheral
    Normal = 0x0,
    /// Wrapped key for SAES mode. Key loaded in key registers can only be used to encrypt or decrypt AES keys. Hence, when a decryption is selected, read-as-zero SAES_DOUTR register is automatically loaded into SAES key registers after a successful decryption process.
    WrappedKey = 0x1,
    /// Shared key mode. After a successful decryption process (unwrapping), SAES key registers are shared with the peripheral described in KSHAREID[1:0] bitfield. This sharing is valid only while KMOD[1:0] at 0x2 and KEYVALID=1. When a decryption is selected, read-as-zero SAES_DOUTR register is automatically loaded into SAES key registers after a successful decryption process.
    SharedKey = 0x2,
    _,
};

pub const KSHAREID = enum(u2) {
    /// AES peripheral
    AES = 0x0,
    _,
};

pub const MODE = enum(u2) {
    Encryption = 0x0,
    /// Key derivation (or key preparation), for ECB/CBC decryption only
    KeyDerivation = 0x1,
    Decryption = 0x2,
    _,
};

/// Secure advanced encryption standard hardware accelerator.
pub const SAES = extern struct {
    /// SAES control register.
    /// offset: 0x00
    CR: mmio.Mmio(packed struct(u32) {
        /// SAES enable This bit enables/disables the SAES peripheral: At any moment, clearing then setting the bit re-initializes the SAES peripheral. This bit is automatically cleared by hardware upon the completion of the key preparation (Mode 2) and upon the completion of GCM/GMAC/CCM initial phase. The bit cannot be set as long as KEYVALID = 0 nor along with the following settings: KMOD = 01 + CHMOD = 011 and KMOD = 01 + CHMOD = 010 + MODE = 00. Note: With KMOD[1:0] other than 00, use the IPRST bit rather than the bit EN.
        EN: u1,
        /// Data type selection This bitfield defines the format of data written in the SAES_DINR register or read from the SAES_DOUTR register, through selecting the mode of data swapping: For more details, refer to . Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
        DATATYPE: DATATYPE,
        /// SAES operating mode This bitfield selects the SAES operating mode: Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
        MODE: MODE,
        /// Chaining mode selection This bitfield selects the AES chaining mode: others: Reserved Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
        CHMOD: u2,
        reserved11: u4 = 0,
        /// DMA input enable This bit enables/disables data transferring with DMA, in the input phase: When the bit is set, DMA requests are automatically generated by SAES during the input data phase. This feature is only effective when Mode 1 or Mode 3 is selected through the MODE[1:0] bitfield. It is not effective for Mode 2 (key derivation).
        DMAINEN: u1,
        /// DMA output enable This bit enables/disables data transferring with DMA, in the output phase: When the bit is set, DMA requests are automatically generated by SAES during the output data phase. This feature is only effective when Mode 1 or Mode 3 is selected through the MODE[1:0] bitfield. It is not effective for Mode 2 (key derivation).
        DMAOUTEN: u1,
        reserved16: u3 = 0,
        /// Chaining mode selection This bitfield selects the AES chaining mode: others: Reserved Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
        CHMOD_CONT: u1,
        reserved18: u1 = 0,
        /// Key size selection This bitfield defines the length of the key used in the SAES cryptographic core, in bits: When KMOD[1:0]=01 or 10 KEYSIZE also defines the length of the key to encrypt or decrypt. Attempts to write the bit are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
        KEYSIZE: KEYSIZE,
        /// Key protection When set, hardware-based key protection is enabled. Attempts to write the bit are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
        KEYPROT: u1,
        reserved24: u4 = 0,
        /// Key mode selection The bitfield defines how the SAES key can be used by the application: Others: Reserved With normal key selection, the key registers are freely usable, no specific usage or protection applies to SAES_DIN and SAES_DOUT registers. With wrapped key selection, the key loaded in key registers can only be used to encrypt or decrypt AES keys. Hence, when a decryption is selected in Wrapped-key mode read-as-zero SAES_DOUT register is automatically loaded into SAES key registers after a successful decryption process. With shared key selection, after a successful decryption process, SAES key registers are shared with the peripheral described in KSHAREID(1:0] bitfield. This sharing is valid only while KMOD[1:0]=10 and KEYVALID = 1. When a decryption is selected, read-as-zero SAES_DOUT register is automatically loaded into SAES key registers after a successful decryption process. With KMOD[1:0] other than zero, any attempt to configure the SAES peripheral for use by an application belonging to a different security domain (secure or non-secure) results in automatic key erasure and setting of the KEIF flag.
        ///Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
        KMOD: KMOD,
        /// Key share identification This bitfield defines, at the end of a decryption process with KMOD[1:0]=10 (shared key), which target can read the SAES key registers using a dedicated hardware bus. Others: Reserved Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
        KSHAREID: KSHAREID,
        /// Key selection The bitfield defines the source of the key information to use in the AES cryptographic core. Others: Reserved (if used, unfreeze SAES with IPRST) When KEYSEL is different from zero, selected key value is available in key registers when BUSY bit is cleared and KEYVALID is set in the SAES_SR register. Otherwise, the key error flag KEIF is set. Repeated writing of KEYSEL[2:0] with the same non-zero value only triggers the loading of DHUK or BHK if KEYVALID = 0. When the application software changes the key selection by writing the KEYSEL[2:0] bitfield, the key registers are immediately erased and the KEYVALID flag cleared. At the end of the decryption process, if KMOD[1:0] is other than zero, KEYSEL[2:0] is cleared. With the bitfield value other than zero and KEYVALID set, the application cannot transfer the ownership of SAES with a loaded key to an application running in another security context (such as secure, non-secure). More specifically, when security of an access to any register does not match the information recorded by SAES, the KEIF flag is set. Attempts to write the bitfield are ignored when the BUSY flag of SAES_SR register is set, as well as when the EN bit of the SAES_CR register is set before the write access and it is not cleared by that write access.
        KEYSEL: KEYSEL,
        /// SAES peripheral software reset Setting the bit resets the SAES peripheral, putting all registers to their default values, except the IPRST bit itself and the SAES_DPACFG register. Hence, any key-relative data is lost. For this reason, it is recommended to set the bit before handing over the SAES to a less secure application. The bit must be low while writing any configuration registers.
        IPRST: u1,
    }),
    /// SAES status register.
    /// offset: 0x04
    SR: mmio.Mmio(packed struct(u32) {
        reserved1: u1 = 0,
        /// Computation completed flag. This bit mirrors the CCF bit of the SAES_ISR register.
        CCF: u1,
        /// Write error This flag indicates the detection of an unexpected write operation to the SAES_DINR register (during computation or data output phase): The flag is set by hardware. It is cleared by software upon setting the RWEIF bit of the SAES_ICR register. Upon the flag setting, an interrupt is generated if enabled through the RWEIE bit of the SAES_ICR register. The flag setting has no impact on the SAES operation. Unexpected write is ignored.
        WRERR: u1,
        /// Busy This flag indicates whether SAES is idle or busy during GCM payload encryption phase: The flag is set upon SAES initialization, upon fetching random number from the RNG, or upon transferring a shared key to a target peripheral. When GCM encryption is selected, the flag must be at zero before selecting the GCM final phase.
        BUSY: u1,
        reserved7: u3 = 0,
        /// Key Valid flag This bit is set by hardware when the amount of key information defined by KEYSIZE in SAES_CR has been loaded in SAES_KEYx key registers. In normal mode when KEYSEL equals to zero, the application must write the key registers in the correct sequence, otherwise the KEIF flag of the SAES_ISR register is set and KEYVALID stays at zero. When KEYSEL is different from zero the BUSY flag is automatically set by SAES. When key is loaded successfully, the BUSY flag is cleared and KEYVALID set. Upon an error, the KEIF flag of the SAES_ISR register is set, the BUSY flag cleared and KEYVALID kept at zero. When the KEIF flag is set, the application must clear it through the SAES_ICR register, otherwise KEYVALID cannot be set. See the KEIF bit description for more details. For more information on key loading please refer to.
        KEYVALID: u1,
        padding: u24 = 0,
    }),
    /// SAES data input register.
    /// offset: 0x08
    DINR: u32,
    /// SAES data output register.
    /// offset: 0x0c
    DOUTR: u32,
    /// SAES key register 0.
    /// offset: 0x10
    KEYR: u32,
    /// offset: 0x14
    reserved20: [12]u8,
    /// SAES initialization vector register 0.
    /// offset: 0x20
    IVR: [4]u32,
    /// offset: 0x30
    reserved48: [16]u8,
    /// SAES suspend registers.
    /// offset: 0x40
    SUSPR: [8]u32,
    /// offset: 0x60
    reserved96: [672]u8,
    /// SAES interrupt enable register.
    /// offset: 0x300
    IER: mmio.Mmio(packed struct(u32) {
        /// Computation complete flag interrupt enable This bit enables or disables (masks) the SAES interrupt generation when CCF (computation complete flag) is set.
        CCFIE: u1,
        /// Read or write error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when RWEIF (read and/or write error flag) is set.
        RWEIE: u1,
        /// Key error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when KEIF (key error flag) is set.
        KEIE: u1,
        /// RNG error interrupt enable This bit enables or disables (masks) the SAES interrupt generation when RNGEIF (RNG error flag) is set.
        RNGEIE: u1,
        padding: u28 = 0,
    }),
    /// SAES interrupt status register.
    /// offset: 0x304
    ISR: mmio.Mmio(packed struct(u32) {
        /// Computation complete flag This flag indicates whether the computation is completed: The flag is set by hardware upon the completion of the computation. It is cleared by software, upon setting the CCF bit of the SAES_ICR register. Upon the flag setting, an interrupt is generated if enabled through the CCFIE bit of the SAES_IER register. The flag is significant only when the DMAOUTEN bit is 0. It may stay high when DMA_EN is 1.
        CCF: u1,
        /// Read or write error interrupt flag This read-only bit is set by hardware when a RDERR or a WRERR error flag is set in the SAES_SR register. RWEIF bit is cleared when application sets the corresponding bit of SAES_ICR register. An interrupt is generated if the RWEIE bit has been previously set in the SAES_IER register. This flags has no meaning when key derivation mode is selected.
        RWEIF: u1,
        /// Key error interrupt flag This read-only bit is set by hardware when key information failed to load into key registers or key register usage is forbidden. Setting the corresponding bit of the SAES_ICR register clears the KEIF and generates interrupt if the KEIE bit of the SAES_IER register is set. KEIF is triggered upon any of the following errors: SAES fails to load the DHUK (KEYSEL = 001 or 100). SAES fails to load the BHK (KEYSEL = 010 or 100) respecting the correct order. AES fails to load the key shared by SAES peripheral (KMOD=10). When KEYVALID = 1 and (KEYPROT = 1 or KEYSEL is not 0x0), the security context of the application that loads the key (secure or non-secure) does not match the security attribute of the access to SAES_CR or SAES_DOUT. In this case, KEYVALID and EN bits are cleared. SAES_KEYRx register write does not respect the correct order. (For KEYSIZE = 0, SAES_KEYR0 then SAES_KEYR1 then SAES_KEYR2 then SAES_KEYR3 register, or reverse. For KEYSIZE = 1, SAES_KEYR0 then SAES_KEYR1 then SAES_KEYR2 then SAES_KEYR3 then SAES_KEYR4 then SAES_KEYR5 then SAES_KEYR6 then SAES_KEYR7, or reverse). KEIF must be cleared by the application software, otherwise KEYVALID cannot be set.
        KEIF: u1,
        /// RNG error interrupt flag This read-only bit is set by hardware when an error is detected on RNG bus interface (e.g. bad entropy). RNGEIE bit is cleared when application sets the corresponding bit of SAES_ICR register. An interrupt is generated if the RNGEIE bit has been previously set in the SAES_IER register. Clearing this bit triggers the reload of a new random number from RNG peripheral.
        RNGEIF: u1,
        padding: u28 = 0,
    }),
    /// SAES interrupt clear register.
    /// offset: 0x308
    ICR: mmio.Mmio(packed struct(u32) {
        /// Computation complete flag clear Setting this bit clears the CCF status bit of the SAES_SR and SAES_ISR registers.
        CCF: u1,
        /// Read or write error interrupt flag clear Setting this bit clears the RWEIF status bit of the SAES_ISR register, and both RDERR and WRERR flags in the SAES_SR register.
        RWEIF: u1,
        /// Key error interrupt flag clear Setting this bit clears the KEIF status bit of the SAES_ISR register.
        KEIF: u1,
        /// RNG error interrupt flag clear Application must set this bit to clear the RNGEIF status bit in SAES_ISR register.
        RNGEIF: u1,
        padding: u28 = 0,
    }),
};
