const microzig = @import("microzig");
const mmio = microzig.mmio;

const types = @import("types.zig");

pub const HIZ = enum(u1) {
    /// VREF+ pin is internally connected to the voltage reference buffer output.
    Connected = 0x0,
    /// VREF+ pin is high impedance.
    HighZ = 0x1,
};

pub const VRS = enum(u3) {
    /// Voltage reference set to VREF_OUT1 (around 2.048 V).
    Vref0 = 0x0,
    /// Voltage reference set to VREF_OUT2 (around 2.5 V).
    Vref1 = 0x1,
    /// Voltage reference set to VREF_OUT2 (around 2.5 V).
    Vref2 = 0x2,
    /// Voltage reference set to VREF_OUT2 (around 2.5 V).
    Vref3 = 0x3,
    _,
};

/// Voltage reference buffer.
pub const VREFBUF = extern struct {
    /// VREFBUF control and status register.
    /// offset: 0x00
    CSR: mmio.Mmio(packed struct(u32) {
        /// Voltage reference buffer mode enable This bit is used to enable the voltage reference buffer mode.
        ENVR: u1,
        /// High impedance mode This bit controls the analog switch to connect or not the VREF+ pin. Refer to for the mode descriptions depending on ENVR bit configuration.
        HIZ: HIZ,
        reserved3: u1 = 0,
        /// Voltage reference buffer ready.
        VRR: u1,
        /// Voltage reference scale These bits select the value generated by the voltage reference buffer. VRS = 000: VREFBUF0 voltage selected. VRS = 001: VREFBUF1 voltage selected. VRS = 010: VREFBUF2 voltage selected. VRS = 011: VREFBUF3 voltage selected. Others: Reserved Note: Refer to the product datasheet for each VREFBUFx voltage setting value. The software can program this bitfield only when the VREFBUF is disabled (ENVR=0).
        VRS: VRS,
        padding: u25 = 0,
    }),
    /// VREFBUF calibration control register.
    /// offset: 0x04
    CCR: mmio.Mmio(packed struct(u32) {
        /// Trimming code The TRIM code is a 6-bit unsigned data (minimum 000000, maximum 111111) that is set and updated according the mechanism described below. Reset: TRIM[5:0] is automatically initialized with the VRS = 0 trimming value stored in the Flash memory during the production test. VRS change: TRIM[5:0] is automatically initialized with the trimming value (corresponding to VRS setting) stored in the Flash memory during the production test. Write in TRIM[5:0]: User can modify the TRIM[5:0] with an arbitrary value. This is permanently disabling the control of the trimming value with VRS (until the device is reset). Note: If the user application performs the trimming, the trimming code must start from 000000 to 111111 in ascending order.
        TRIM: u6,
        padding: u26 = 0,
    }),
};
