const Patch = @import("microzig/build-internals").Patch;

pub const patches: []const Patch = &.{
    .{
        .add_enum = .{
            .parent = "types.peripherals.PADS_BANK0",
            .@"enum" = .{
                .name = "DriveStrength",
                .bitsize = 2,
                .fields = &.{
                    .{ .value = 0x0, .name = "2mA" },
                    .{ .value = 0x1, .name = "4mA" },
                    .{ .value = 0x2, .name = "8mA" },
                    .{ .value = 0x3, .name = "12mA" },
                },
            },
        },
    },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO0.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO1.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO2.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO3.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO4.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO5.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO6.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO7.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO8.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO9.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO10.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO11.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO12.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO13.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO14.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO15.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO16.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO17.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO18.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO19.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO20.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO21.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO22.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO23.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO24.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO25.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO26.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO27.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO28.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO29.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO30.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO31.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO32.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO33.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO34.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO35.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO36.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO37.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO38.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO39.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO40.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO41.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO42.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO43.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO44.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO45.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO46.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.PADS_BANK0.GPIO47.DRIVE", .to = "types.peripherals.PADS_BANK0.DriveStrength" } },
    .{ 
        .add_enum = .{
        .parent = "types.peripherals.USB_DPRAM",
        .@"enum" = .{
            .name = "EndpointType",
            .bitsize = 2,
            .fields = &.{
                .{ .value = 0x0, .name = "control" },
                .{ .value = 0x1, .name = "isochronous" },
                .{ .value = 0x2, .name = "bulk" },
                .{ .value = 0x3, .name = "interrupt" },
            },
        },
    } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP1_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP1_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP2_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP2_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP3_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP3_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP4_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP4_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP5_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP5_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP6_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP6_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP7_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP7_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP8_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP8_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP9_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP9_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP10_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP10_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP11_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP11_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP12_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP12_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP13_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP13_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP14_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP14_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP15_IN_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.USB_DPRAM.EP15_OUT_CONTROL.ENDPOINT_TYPE", .to = "types.peripherals.USB_DPRAM.EndpointType" } },
    .{
        .add_enum = .{
            .parent = "types.peripherals.DMA",
            .@"enum" = .{
                .name = "DataSize",
                .bitsize = 2,
                .fields = &.{
                    .{ .value = 0x0, .name = "size_8" },
                    .{ .value = 0x1, .name = "size_16" },
                    .{ .value = 0x2, .name = "size_32" },
                },
            },
        },
    },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH0_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH1_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH2_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH3_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH4_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH5_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH6_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH7_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH8_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH9_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH10_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH11_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH12_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH13_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH14_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH15_CTRL_TRIG.DATA_SIZE", .to = "types.peripherals.DMA.DataSize" } },
    .{
        .add_enum = .{
            .parent = "types.peripherals.DMA",
            .@"enum" = .{
                .name = "Dreq",
                .bitsize = 6,
                .fields = &.{
                    .{ .value = 0, .name = "pio0_tx0" },
                    .{ .value = 1, .name = "pio0_tx1" },
                    .{ .value = 2, .name = "pio0_tx2" },
                    .{ .value = 3, .name = "pio0_tx3" },
                    .{ .value = 4, .name = "pio0_rx0" },
                    .{ .value = 5, .name = "pio0_rx1" },
                    .{ .value = 6, .name = "pio0_rx2" },
                    .{ .value = 7, .name = "pio0_rx3" },
                    .{ .value = 8, .name = "pio1_tx0" },
                    .{ .value = 9, .name = "pio1_tx1" },
                    .{ .value = 10, .name = "pio1_tx2" },
                    .{ .value = 11, .name = "pio1_tx3" },
                    .{ .value = 12, .name = "pio1_rx0" },
                    .{ .value = 13, .name = "pio1_rx1" },
                    .{ .value = 14, .name = "pio1_rx2" },
                    .{ .value = 15, .name = "pio1_rx3" },
                    .{ .value = 16, .name = "pio2_tx0" },
                    .{ .value = 17, .name = "pio2_tx1" },
                    .{ .value = 18, .name = "pio2_tx2" },
                    .{ .value = 19, .name = "pio2_tx3" },
                    .{ .value = 20, .name = "pio2_rx0" },
                    .{ .value = 21, .name = "pio2_rx1" },
                    .{ .value = 22, .name = "pio2_rx2" },
                    .{ .value = 23, .name = "pio2_rx3" },
                    .{ .value = 24, .name = "spi0_tx" },
                    .{ .value = 25, .name = "spi0_rx" },
                    .{ .value = 26, .name = "spi1_tx" },
                    .{ .value = 27, .name = "spi1_rx" },
                    .{ .value = 28, .name = "uart0_tx" },
                    .{ .value = 29, .name = "uart0_rx" },
                    .{ .value = 30, .name = "uart1_tx" },
                    .{ .value = 31, .name = "uart1_rx" },
                    .{ .value = 32, .name = "pwm_wrap0" },
                    .{ .value = 33, .name = "pwm_wrap1" },
                    .{ .value = 34, .name = "pwm_wrap2" },
                    .{ .value = 35, .name = "pwm_wrap3" },
                    .{ .value = 36, .name = "pwm_wrap4" },
                    .{ .value = 37, .name = "pwm_wrap5" },
                    .{ .value = 38, .name = "pwm_wrap6" },
                    .{ .value = 39, .name = "pwm_wrap7" },
                    .{ .value = 40, .name = "pwm_wrap8" },
                    .{ .value = 41, .name = "pwm_wrap9" },
                    .{ .value = 42, .name = "pwm_wrap10" },
                    .{ .value = 43, .name = "pwm_wrap11" },
                    .{ .value = 44, .name = "i2c0_tx" },
                    .{ .value = 45, .name = "i2c0_rx" },
                    .{ .value = 46, .name = "i2c1_tx" },
                    .{ .value = 47, .name = "i2c1_rx" },
                    .{ .value = 48, .name = "adc" },
                    .{ .value = 49, .name = "xip_stream" },
                    .{ .value = 50, .name = "xip_qmitx" },
                    .{ .value = 51, .name = "xip_qmirx" },
                    .{ .value = 52, .name = "hstx" },
                    .{ .value = 53, .name = "coresight" },
                    .{ .value = 54, .name = "sha256" },
                    .{ .value = 59, .name = "timer0" },
                    .{ .value = 60, .name = "timer1" },
                    .{ .value = 61, .name = "timer2" },
                    .{ .value = 62, .name = "timer3" },
                    .{ .value = 63, .name = "permanent" },
                },
            },
        },
    },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH0_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH1_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH2_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH3_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH4_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH5_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH6_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH7_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH8_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH9_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH10_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH11_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH12_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH13_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH14_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .set_enum_type = .{ .of = "types.peripherals.DMA.CH15_CTRL_TRIG.TREQ_SEL", .to = "types.peripherals.DMA.Dreq" } },
    .{ .add_interrupt = .{
        .device_name = "RP2350",
        .idx = 40,
        .name = "PROC0_IRQ_CTI",
    } },
    .{ .add_interrupt = .{
        .device_name = "RP2350",
        .idx = 41,
        .name = "PROC1_IRQ_CTI",
    } },
    .{ .add_interrupt = .{
        .device_name = "RP2350",
        .idx = 46,
        .name = "SPAREIRQ_IRQ_0",
    } },
    .{ .add_interrupt = .{
        .device_name = "RP2350",
        .idx = 47,
        .name = "SPAREIRQ_IRQ_1",
        .description = "Spare interrupt 1 (triggered only by software)",
    } },
    .{ .add_interrupt = .{
        .device_name = "RP2350",
        .idx = 48,
        .name = "SPAREIRQ_IRQ_2",
        .description = "Spare interrupt 2 (triggered only by software)",
    } },
    .{ .add_interrupt = .{
        .device_name = "RP2350",
        .idx = 49,
        .name = "SPAREIRQ_IRQ_3",
        .description = "Spare interrupt 3 (triggered only by software)",
    } },
    .{ .add_interrupt = .{
        .device_name = "RP2350",
        .idx = 50,
        .name = "SPAREIRQ_IRQ_4",
        .description = "Spare interrupt 4 (triggered only by software)",
    } },
    .{ .add_interrupt = .{
        .device_name = "RP2350",
        .idx = 51,
        .name = "SPAREIRQ_IRQ_5",
        .description = "Spare interrupt 5 (triggered only by software)",
    } },
};
