name: Reusable binary publish workflow

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        default: ""
        description: The version tag to publish
      github-artifact-name:
        required: true
        type: string
        description: The github artifact to download the artifact from.
      artifact-name:
        required: true
        type: string
        description: The name of what we are publishing
      # The path after the target-path to publish the artifact to
      # {artifact | {target-path}/{target-artifact-path}
      target-artifact-path:
        required: false
        type: string
        default: ""
        description: |
          The path that goes after target-path to specify a subdirectory
          to publish to. Final path: {target-path}/{target-artifact-path}
      # The path within the github artifact that the artifact is located at.
      source-path:
        required: false
        type: string
        default: ""
        description: |
          The path within the github artifact where the artifact is located at
    secrets:
      # The target path within the host share to save files to
      target-path:
        required: true
        description: |
          The path within the host machine where the data should be published
          to.
      ssh-key:
        required: true
        description: The ssh private key that is used to publish to the host.
      host:
        required: true
        description: The host that has sshd running to publish to.
      port:
        required: true
        description: The port the host is running sshd on.
      user:
        required: true
        description: THe username to log in to the server as.

jobs:
  publish:
    runs-on: macos-latest
    steps:
      # If this is somehow not run from a tag, fail. This is a remainder from
      # when the build side and publish side were done in one workflow.
      - name: Check tag status
        if: |
          startsWith(github.ref, 'refs/tags/') 
            && ! endsWith(github.ref, inputs.tag)
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed("Provided tag does not match github ref tag")
      # Download the requested github artifact
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.github-artifact-name }}
      # Get the path to where the artifact is at. This is the path to the
      # downloaded artifact that is relative to the github workspace with the
      # source-path parameter tacked on the end.
      - name: Get Source Path
        shell: bash
        id: get-source-path
        run: |
          echo "path=$( \
            realpath -s --relative-to="${{ github.workspace }}" \
            "${{ steps.download.outputs.download-path }}/${{ inputs.source-path }}" \
            )" >> $GITHUB_OUTPUT
      # Publish to the host
      - name: Publish Release
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.ssh-key }}
          ARGS: "-vzrli"
          SOURCE: ${{ steps.get-source-path.outputs.path }}
          REMOTE_HOST: ${{ secrets.host }}
          REMOTE_USER: ${{ secrets.user }}
          REMOTE_PORT: ${{ secrets.port }}
          TARGET: ${{ secrets.target-path }}/${{ inputs.target-artifact-path }}
      # (Not working as intented) Un-needed for now. This step would go through
      # every binary and folder within the source path and add it to the release
      # if it were a file, or compress it and then add the compressed file to
      # the release.
      # Issue: Adds things that are not desired in the output.
      #- name: Handle Folder Release Artifact
      #  if: ${{ startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, inputs.tag) }}
      #  shell: bash
      #  run: |
      #    mkdir -p "artifacts-${{ github.sha }}"
      #    for i in "${{ steps.download.outputs.download-path }}/${{ inputs.source-path }}"/*; do
      #      echo "Artifact path $i"
      #      if [[ -d "$i" ]]; then
      #        echo "Artifact is path"
      #        dirname="$(basename "$i")"
      #        echo "Artifact directory $dirname. Compressing folder to ${{ inputs.artifact-name }}-${dirname}.tar.gz"
      #        tar -czvf "${{ inputs.artifact-name }}-${dirname}.tar.gz" -C "$i" .
      #        echo "Moving tar to artifacts-${{ github.sha }}"
      #        mv "${{ inputs.artifact-name }}-${dirname}.tar.gz" "artifacts-${{ github.sha }}"
      #      else
      #        echo "Artifact is file"
      #        echo "Move to: artifacts-${{ github.sha }}"
      #        mv "$i" "artifacts-${{ github.sha }}"
      #      fi
      #    done
      # Create the release draft on GitHub.
      - name: Create Release Draft
        if: ${{ startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, inputs.tag) }}
        uses: ncipollo/release-action@v1
        with:
          # artifacts: "artifacts-${{ github.sha }}/*"
          # artifactErrorsFailBuild: true
          draft: true
          generateReleaseNotes: true
          tag: ${{ inputs.tag }}
          prerelease: ${{ contains(inputs.tag, '-beta') || contains(inputs.tag, '-alpha') || contains(inputs.tag, '-rc') }}
