name: Readme version check

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # Ensure that the zig version found in build.zig.zon is present in the readme
  readme-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - run: |
          DOC_FILES="README.md website/content/docs/getting-started.smd"
          EXIT_CODE=0
          CURRENT_VERSION=$(cat build.zig.zon | sed -n 's/.*\.minimum_zig_version = "\(.*\)",/\1/p')
          echo current version: $CURRENT_VERSION
          for FILE in $DOC_FILES
          do
              if ! grep -q $CURRENT_VERSION $FILE
              then
                  echo Zig version documented in \'$FILE\' out of sync with build.zig.zon
                  EXIT_CODE=1
              fi
          done

          exit $EXIT_CODE
