name: sim/aviron
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Build
        working-directory: sim/aviron
        run: zig build install

      - name: Run Test Suite
        working-directory: sim/aviron
        run: zig build test

      - name: Run Samples
        working-directory: sim/aviron
        run: |
          ./zig-out/bin/aviron --info
          ./zig-out/bin/aviron --trace zig-out/samples/math.elf
          ./zig-out/bin/aviron zig-out/samples/hello-world.elf
