name: tools/sorcerer
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Setup SDL3
        uses: libsdl-org/setup-sdl@main
        with:
          version: sdl3-latest

      - name: Build
        working-directory: tools/sorcerer
        run: zig build

      - name: Run Test Suite
        working-directory: tools/sorcerer
        run: zig build test
