name: Reusable zig build workflow

on:
  workflow_call:
    inputs:
      zig-version:
        required: false
        type: string
        default: 0.13.0
      get-submodules:
        required: false
        type: string
        default: false
      sparse-checkout-patterns:
        required: false
        type: string
        default: ""
      working-directory:
        required: false
        type: string
        default: "."
      is-packaged:
        required: false
        type: boolean
        default: false
      github-artifact-name:
        required: true
        type: string
      artifact-output-paths:
        required: true
        type: string
    secrets:
      downloads-url:
        required: false

jobs:
  build-zig:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@4
        with:
          sparse-checkout: ${{ input.sparse-checkout-patterns }}
          submodules: ${{ input.get-submodules }}
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ inputs.zig-version }}
      - name: Build
        if: ${{ ! inputs.is-packaged }}
        run: zig build -Doptimize=ReleaseSmall
        working-directory: ${{ inputs.working-directory }}
      - name: Package
        if: ${{ inputs.is-packaged }}
        run: zig build package -- "${{ secrets.downloads-url }}"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.github-artifact-name }}
          path: ${{ input.artifact-output-paths }}
