name: Reusable zig build workflow

on:
  workflow_call:
    inputs:
      # The version to build on
      zig-version:
        required: false
        type: string
        default: 0.13.0
      # Whether or not to clone submodules
      get-submodules:
        required: false
        type: string
        default: false
      # If using sparse checkout, the file patterns to include when cloning
      sparse-checkout-patterns:
        required: false
        type: string
        default: ""
      # If building a subproject only, you can specify a working directory
      # which is the path to that subproject.
      working-directory:
        required: false
        type: string
        default: "."
      # Whether or not to use a provided package command.
      is-packaged:
        required: false
        type: boolean
        default: false
      # The github artifact name for uploading build artifacts to
      # If it is blank, nothing will be uploaded
      github-artifact-name:
        required: false
        type: string
        default: ""
      # The path that we should upload artifacts from
      artifact-output-paths:
        required: true
        type: string
      ref:
        required: false
        type: string
        default: ""
    secrets:
      # The downloads url for the packaging step. This is used in boxzer to
      # fill in the manifest downloads location
      downloads-url:
        required: false

jobs:
  build-zig:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest, macos-latest]
    steps:
      - name: Checkout
        if: ${{ inputs.ref == '' }}
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.sparse-checkout-patterns }}
          submodules: ${{ inputs.get-submodules }}
      - name: Checkout Specific Ref
        if: ${{ inputs.ref != '' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          sparse-checkout: ${{ inputs.sparse-checkout-patterns }}
          submodules: ${{ inputs.get-submodules }}
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ inputs.zig-version }}
      - name: Build
        if: ${{ ! inputs.is-packaged || runner.os != 'macOS' }}
        run: zig build -Doptimize=ReleaseSmall
        working-directory: ${{ inputs.working-directory }}
      - name: Package
        if: ${{ inputs.is-packaged && runner.os == 'macOS' }}
        run: zig build package -- "${{ secrets.downloads-url }}"
      - name: Upload Artifacts
        if: ${{ inputs.artifact-output-paths == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.github-artifact-name }}
          path: ${{ inputs.artifact-output-paths }}
